"""elite_pgvector_and_premium_fields

Revision ID: 619120609684
Revises: 841aa1f7d834
Create Date: 2026-03-20 11:40:50.312658+00:00

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '619120609684'
down_revision = '841aa1f7d834'
branch_labels = None
depends_on = None

def upgrade():
    # Ensure extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('mode', sa.String(length=50), nullable=True, server_default='basic'))
    op.add_column('extractions', sa.Column('input_type', sa.String(length=50), nullable=True, server_default='text'))
    
    # Make columns NOT NULL after setting default for existing rows if needed.
    # For simplicity here we use server_default which handles existing rows in some DBs,
    # but specifically for String we should be careful.
    op.execute("UPDATE extractions SET mode = 'basic' WHERE mode IS NULL")
    op.execute("UPDATE extractions SET input_type = 'text' WHERE input_type IS NULL")
    op.alter_column('extractions', 'mode', nullable=False)
    op.alter_column('extractions', 'input_type', nullable=False)

    op.add_column('semantic_memory', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.create_index(op.f('ix_semantic_memory_embedding'), 'semantic_memory', ['embedding'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_memory_embedding'), table_name='semantic_memory')
    op.drop_column('semantic_memory', 'embedding')
    op.drop_column('extractions', 'input_type')
    op.drop_column('extractions', 'mode')
    # ### end Alembic commands ###
